application: graphdog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /images/.*\.png
  static_files: static/images/.*\.png
  upload: static/images/.*\.png

- url: /command/1/.*
  script: command1.app

- url: /command/2/.*
  script: command2.app

- url: /command/3/.*
  script: command3.app

- url: /command/4/.*
  script: command4.app

- url: /command/5/.*
  script: command5.app

- url: /command
  script: command0.app

- url: /command/.*
  script: command0.app

#- url: /stats.*
#  script: google.appengine.ext.appstats.ui.app

- url: /.*
  script: main.app

#builtins:
#- appstats: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: "2.6"
